favourite stocks
zaharovroman/stock_app pull request #2
Opened 2022-03-17 16:47 UTC by zaharovroman

2022-03-18 06:54 UTC, vasbaza requested changes

2022-03-18 06:54 UTC, vasbaza commented on lib/data/repository/stock_repository/stock_repository_service.dart
>    final _token = 'pk_0e64607a9fec4dd5a35f4d4e3e799e1c';
Вынеси куда-нибудь в константу

2022-03-18 06:54 UTC, vasbaza commented on lib/data/repository/stock_repository/stock_repository_service.dart
> +      '/stable/stock/$symbol/quote/',
Вынеси в константу

2022-03-18 06:54 UTC, vasbaza commented on lib/presentation/app/app.dart
> +        body: widget.tabs[_currentTab],
Может быть обернуть в IndexedStack, чтобы при переключении между табами каждый раз не создавалась вмка?

2022-03-18 06:54 UTC, vasbaza commented on lib/presentation/app/app.dart
> +                  label: 'List',
Такие штуки как 'List' и 'Favourite' лучше выносить в enum

2022-03-18 06:54 UTC, vasbaza commented on lib/presentation/home/home_screen.dart
> +        return ValueListenableBuilder<List<Stock>>(
Попробуй здесь заюзать EntityStateNotifierBuilder, и сделать обработку состояния загрузки (loader builder) и ошибки (error builder)

2022-03-18 06:54 UTC, vasbaza commented on lib/presentation/navigation/router.dart
> +  // RouterDelegate get routerDelegate => _goRouter.routerDelegate;
Закомменченный код лучше не оставлять, а если есть такая необходимость - ставь todo в таком формате: 
`// TODO(name): to do something`

2022-03-18 06:54 UTC, vasbaza commented on lib/presentation/widgets/stock_card.dart
> +  final Function()? onFavouriteTaped;
Вместо Function()? можно поставить VoidCallback?

2022-03-18 06:54 UTC, vasbaza commented on lib/presentation/widgets/stock_card.dart
> +                            color: Colors.red,
Для цветов приложения можешь создать отдельный класс типо AppColors и вынести туда все цвета

2022-03-18 06:54 UTC, vasbaza commented on test/widget_test.dart
>      expect(find.text('0'), findsOneWidget);
не очень полезный тест, лучше его убрать или добавить какую-то проверку, которая относится к твоему приложению

2022-03-18 06:54 UTC, vasbaza commented on lib/presentation/widgets/stock_card.dart
> +                    onPressed: onFavouriteTaped,
При тапе есть небольшая задержка из-за future, можешь попробовать обработать этот кейс: например, добавить значок загрузки или сразу менять состояния на favourite (не дожидаясь исполнения future), а при ошибке выбрасывать снекбар и менять состояние обратно)

2022-03-18 06:54 UTC, vasbaza commented on lib/main.dart
> +  await Hive.initFlutter();
Лучше вынести куда-нибудь инициализацию Hive, а здесь просто оставить что-то типо initStorage. Вообще сам по себе Hive стоит спрятать, чтобы не зависеть от конкретной имплементации

2022-03-18 06:54 UTC, vasbaza commented on lib/presentation/favourite/favourite_wm.dart
> +  void tapOnFavourite(Stock stock) {
Вроде как асинхронная функция

2022-03-18 06:54 UTC, vasbaza commented on lib/presentation/favourite/favourite_screen.dart
> +                    wm.tapOnFavourite(stock);
Нужна обработка состояния загрузки

2022-03-18 09:32 UTC, zaharovroman commented on lib/presentation/app/app.dart
> +                  label: 'List',
Почему именно enum, а не в константы?

2022-03-18 14:26 UTC, vasbaza commented on lib/presentation/app/app.dart
> +                  label: 'List',
да, сорри, это я невнимательно посмотрела
оставь как есть

2022-03-22 06:20 UTC, vasbaza approved these changes

2022-03-22 06:20 UTC, merged